### ISSUE TITLE
OMake mailing list is down

### ISSUE THREAD

**Issue by nshibano** [gerdstolpmann/omake#13]
Hi,

Mailing list linked from original site(http://omake.metaprl.org/omake_lists.html) is not accessible now.

Is this temporary down?

**Comment by gerdstolpmann** [comment]
AFAIK the list does not exist anymore.

**Comment by nshibano** [comment]
Thanks for your info.

I think ML is needed. Do you have any plan to open new one?

Also, I felt that it will be helpful if I can read the archive of ML from beginning of the project. Are they lost now?

**Comment by nshibano** [comment]
Some part of archive is available in gmane.

http://dir.gmane.org/search.php?match=omake

In gmane, omake-general, omake-annouce and omake-cvs is available. But omake and omake-devel are missing.

**Comment by rgrinberg** [comment]
+1 for a mailing list

**Comment by gerdstolpmann** [comment]
Do you have any suggestions where to start it?

I still have some mailing list software at hand on camlcity.org, but it was unmaintained for some time, and would need some maintenance. It would be nice if I could avoid that - running a mailing list is no fun anymore.

**Comment by nshibano** [comment]
Yeah, it is no fun to maintain ML, especially when mail-delivery problem happen.

I know https://sourceforge.net provides ML. But there could be something else better?

**Comment by rgrinberg** [comment]
I have a feeling that ocaml.org might run some mailing lists http://ocaml.org/community/mailing_lists.html. Perhaps they can help?

@avsm @agarwal any recommendations?

**Comment by amirmc** [comment]
Yup, a mailing list can be set up at lists.ocaml.org. Just send an email to infrastructure@lists.ocaml.org with basic info (i.e. name of list, who the admin should be, etc).

**Comment by rgrinberg** [comment]
Thanks @amirmc .

@gerdstolpmann Are you fine with using ocaml.org?

**Comment by avsm** [comment]
Yes a short email to the infrastructure list for the archives is all that is needed (so that we know who to set for moderation and so on). lists.ocaml.org is a standard mailman setup.

**Comment by gerdstolpmann** [comment]
Ok, sent the request. If anybody could take the role of a co-moderator this would be appreciated (but is not required).

**Comment by gerdstolpmann** [comment]
There is it: http://lists.ocaml.org/listinfo/omake

Thanks, Anil!

**Comment by nshibano** [comment]
Thanks Gerd and all!
