### ISSUE TITLE
Generate .cmxs files

### ISSUE THREAD

**Issue by rgrinberg** [gerdstolpmann/omake#16]
Is there a way to do this? I've had a brief look at `OCaml.om` and it seems like the `-shared` option isn't used anywhere. Would be great if this was supported by omake or there was at least a decent workaround.

**Comment by nshibano** [comment]
I think current OMake libraries doesn't support that, and adding some lines to OCamlLibrary() function will add that functionality. To do that, you can tweak your system-wide OCaml.om or, copy it to your user folder with different name (for example OCaml2.om or something) and modify it and open it in your OMakeroot.

Or if you need things just work, I think you can start with very specific build rules in your OMakefile. (Personally I prefer this way. In my projects I don't use OMake libraries at all.) For example, to build bar.cmxs from foo.ml:

```
# Rules for foo.cmx from foo.ml is contained in library build/OCaml.
open build/OCaml

bar.cmxs : foo.cmx
  ocamlopt -shared foo.cmx -o bar.cmxs
```

And you can modify this to make it more generic and useful.

**Comment by gerdstolpmann** [comment]
Last year I developed an omake plugin for oasis (https://github.com/ocaml/oasis/pull/68). It is not yet merged. It includes some new OMake functions that are interesting here, and I wonder what functionality should be ported back to OMake (look for oasis_lib.om). Adding a rule for cmxs is only one thing (the easiest), Another feature would be the support for linking in C objects.

**Comment by rgrinberg** [comment]
@nshibano I don't disagree with your approach of writing rules from scratch but I definitely don't think it should be the only way.

Thanks @gerdstolpmann I'll take a look.

**Comment by nshibano** [comment]
@rgrinberg Yes of cause. There is many way. OMake provides that flexibility. I didn't meant to push my way to anybody. Sorry if my post had sound rude.

**Comment by rgrinberg** [comment]
@nshibano not at all, it was entirely polite and informative. Thanks again.

Recently, I've ported one of my OCaml projects from oasis to omake and I've found omake to require a little too much boilerplate - https://github.com/rgrinberg/opium/blob/master/OMakefile. I like the fact that omake provides with great flexibility but I do think that there should be simple, boiler plate free ways for people to use it with common project types. I'd hate to have to write OCaml rules from scratch for such a simple project.

**Comment by nshibano** [comment]
I think this one is well re-factored and the OMakefile is necessarily complex because the task is complex. (For example this script supports multiple conditions of libraries provided.)

But also agree that there should be working baseline for everyone in the official library.
