### ISSUE TITLE
Collision of hashing function for large files

### ISSUE THREAD

**Issue by sbriais** [gerdstolpmann/omake#27]
At LexiFi, we have a case where a very simple diff to a source file (basically accessing another field of a record) make produce a library file such that:
- the .cmxa file is identical, hence same digest
- the .a file is different but have the same digest from the point of view of omake. Indeed, the .a file is considered as being large by omake and thus the hashing function is not MD5 but a "sloppy" hashing function.
Thus, omake was not able to build correctly our tree. 

I tried a patched version of omake where digest_file is always a call to Digest.file (thus solving the problem). The speed difference is not very big (4m13s vs 4m9s) so I suggest digest_file is always a call to Digest.file so that we avoid these easy collisions.

**Comment by gerdstolpmann** [comment]
Removed the sloppy hash function. Now MD5 is always used.

An alternate approach would be to use a cheaper checksum function for large files that doesn't skip over file parts, but just uses a simpler accumulation, like the Unix cksum utility.
