### ISSUE TITLE
OCAMLDEP_MODULES_ENABLED doesn't add current dir to include path

### ISSUE THREAD

**Issue by gerdstolpmann** [gerdstolpmann/omake#8]
Normal `ocamldep` always finds modules in the current directory. When `ocamldep -modules` is enabled, though, the lookup of the files implementing the modules is no longer done inside `ocamldep` but done in a postprocessing step inside omake. This postprocessing step doesn't add the current directory to the search path.

For users this means they should set
```
OCAMLINCLUDES += .
```
when they set `OCAMLDEP_MODULES_ENABLED = true` (which is even the default).

As the current dir is always searched by ocamlc/ocamlopt there is no point not to add the current directory to `OCAMLINCLUDES`.

**Comment by alainfrisch** [comment]
People might be using `-nostdlib` and prefer to be fully explicit with the include dirs, and this change might break such scenario.

**Comment by gerdstolpmann** [comment]
Suggested fix is a new variable `OCAMLINCLUDES_FOR_OCAMLDEP_MODULES` that defaults to ".". It is additionally considered for the `ocamldep -modules` postprocessing step. The default ensures compatibility with plain `ocamldep` even if `OCAMLINCLUDES` is changed. Nevertheless, the user has still full control and can change the default.
